Migrate to Gradle.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,50 +2,65 @@ name: Release
 
 on:
   push:
-    branches: [ master ]
+    branches:
+      - master
 
 jobs:
   release:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-      - name: Set up Java, Maven
-        uses: actions/setup-java@v1
+      - name: Set up Java 21
+        uses: actions/setup-java@v3
         with:
-          java-version: 17
-          server-id: ossrh
-          server-username: MAVEN_USERNAME
-          server-password: MAVEN_PASSWORD
-          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
-          gpg-passphrase: MAVEN_GPG_PASSPHRASE
+          distribution: 'temurin'
+          java-version: '21'
 
-      - name: Extract last version tag
+      - name: Extract Last Version Tag
+        id: previoustag
         uses: oprypin/find-latest-tag@v1
         with:
           repository: ${{ github.repository }}
           prefix: v
-        id: previoustag
 
-      - name: Retreive version from pom
-        shell: bash
-        run: echo "##[set-output name=version;]$(echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout))"
-        id: retreive_version
+      - name: Retrieve Version from Gradle
+        id: retrieve_version
+        run: |
+          VERSION=$(./gradlew -q printVersion)
+          if [[ -z "$VERSION" ]]; then
+            echo "Error: Version extraction failed!" >&2
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
 
-      - name: Resolve new tag name
-        shell: bash
-        run: echo "##[set-output name=tag;]$(echo v${{ steps.retreive_version.outputs.version }})"
+      - name: Resolve New Tag Name
         id: resolve_new_tag_name
+        run: |
+          echo "tag=v${{ steps.retrieve_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
 
-      - name: Release
+      - name: Print Version information
+        run: |
+          echo "Extracted Version: ${{ steps.retrieve_version.outputs.VERSION }}"
+          echo "Resolved Tag: ${{ steps.resolve_new_tag_name.outputs.tag }}"
+
+      - name: Import GPG Key
+        run: |
+          echo "${{ secrets.SIGNING_PRIVATE_KEY }}" | gpg --batch --yes --no-tty --import
+          echo "${{ secrets.SIGNING_PASSWORD }}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --export-secret-keys > /tmp/secret.gpg
+
+      - name: Release to Sonatype
         if: ${{ steps.previoustag.outputs.tag != steps.resolve_new_tag_name.outputs.tag }}
-        run: mvn deploy --no-transfer-progress
+        run: |
+          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon \
+            -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
+            -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
+            -Psigning.secretKeyRingFile=/tmp/secret.gpg
         env:
-          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
-          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
-          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
+          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
+          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
 
       - name: Create Tag
         if: ${{ steps.previoustag.outputs.tag != steps.resolve_new_tag_name.outputs.tag }}
